// test-files/preact/test.tsx
// Test file to validate Preact ESLint configuration
import { h, Fragment } from 'preact';
import { useState } from 'preact/hooks';

// Unused import (should be caught by base config)

// Unused variable (should be caught by base config)
const unusedVar = 'test';

// Preact component with various violations
const TestComponent = () => {
  const [count, setCount] = useState(0);

  return (
    <div>
      {/* Missing alt attribute (accessibility violation) */}
      <img src="/test.jpg" />

      {/* Anchor without proper text */}
      <a href="/test">click here</a>

      {/* Useless fragment */}
      <Fragment>
        <span>text</span>
      </Fragment>

      {/* Forbidden HTML elements from React config */}
      <b>Bold text</b>
      <i>Italic text</i>

      {/* Button with handler */}
      <button onClick={() => setCount(count + 1)}>Count: {count}</button>
    </div>
  );
};

export default TestComponent;

// test-files/angular/test.component.ts
// Test file to validate Angular ESLint configuration
import { Component, Directive, Input } from '@angular/core';
import { HttpClient } from '@angular/common/http';

// Unused import (should be caught by base config)

// Unused variable (should be caught by base config)
const unusedVar = 'test';

// Wrong component selector prefix (should be 'app', not 'my')
@Component({
  selector: 'my-test-component',
  template: `
    <div>
      <button>Click me</button>
    </div>
  `,
})
export class TestComponent {
  @Input() data: any;

  constructor(private http: HttpClient) {}
}

// Wrong directive selector prefix (should be 'app', not 'my')
// Wrong style (should be camelCase, not kebab-case)
@Directive({
  selector: '[my-highlight]',
})
export class HighlightDirective {
  constructor() {}
}

<!-- Test file to validate Angular template ESLint configuration -->

<!-- Missing alt attribute on image (accessibility violation) -->
<img src="test.jpg">

<!-- Empty alt attribute (accessibility violation) -->
<img src="test.jpg" alt="">

<!-- Click handler without keyboard support (accessibility violation) -->
<div (click)="handleClick()">Click me</div>

<!-- Missing label for form control (accessibility violation) -->
<input type="text">

<!-- Autofocus is problematic for accessibility -->
<input type="text" autofocus>
