// test-files/angular/test.component.ts
// Test file to validate Angular ESLint configuration
import { Component, Directive, Input } from '@angular/core';
import { HttpClient } from '@angular/common/http';

// Unused import (should be caught by base config)

// Unused variable (should be caught by base config)
const unusedVar = 'test';

// Wrong component selector prefix (should be 'app', not 'my')
@Component({
  selector: 'my-test-component',
  template: `
    <div>
      <button>Click me</button>
    </div>
  `,
})
export class TestComponent {
  @Input() data: any;

  constructor(private http: HttpClient) {}
}

// Wrong directive selector prefix (should be 'app', not 'my')
// Wrong style (should be camelCase, not kebab-case)
@Directive({
  selector: '[my-highlight]',
})
export class HighlightDirective {
  constructor() {}
}

<!-- Test file to validate Angular template ESLint configuration -->

<!-- Missing alt attribute on image (accessibility violation) -->
<img src="test.jpg">

<!-- Empty alt attribute (accessibility violation) -->
<img src="test.jpg" alt="">

<!-- Click handler without keyboard support (accessibility violation) -->
<div (click)="handleClick()">Click me</div>

<!-- Missing label for form control (accessibility violation) -->
<input type="text">

<!-- Autofocus is problematic for accessibility -->
<input type="text" autofocus>

// test-files/nextjs/test.tsx
// Test file to validate Next.js ESLint configuration
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';

// Unused import (should be caught by base config)

// Unused variable (should be caught by base config)
const unusedVar = 'test';

// Anonymous default export (should trigger warning)
export default function () {
  const [count, setCount] = useState(0);
  const router = useRouter();

  // useEffect with missing dependency (should be caught by react-hooks)
  useEffect(() => {
    console.log(count);
  }, []);

  // Conditional hook call (violates rules of hooks)
  if (count > 0) {
    useEffect(() => {
      console.log('conditional effect');
    }, []);
  }

  return (
    <div>
      {/* Using img instead of next/image (Next.js violation) */}
      <img src="/test.jpg" alt="Test" />

      {/* Using anchor tag for internal navigation instead of next/link */}
      <a href="/about">About page</a>

      {/* Missing alt attribute (accessibility violation) */}
      <img src="/another.jpg" />

      {/* Forbidden HTML elements from base React config */}
      <b>Bold text</b>
      <i>Italic text</i>

      <button onClick={() => setCount(count + 1)}>Count: {count}</button>
    </div>
  );
}
